[package]
name = "binary_search_tree"
version = "0.1.0"
authors = ["alex.sharov <alex.sharov@lazada.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
rand = "0.7"
rand_distr = "0.2"

